/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

import (
	"time"
)

// WebHook represents the response format for a webhook
type WebHook struct {
	Attributes *WebHookAttributes `json:"attributes,omitempty"`
	// The creation timestamp of the workloadcluster
	Created time.Time `json:"created,omitempty"`
	// The description for the WebHook
	Description string `json:"description,omitempty"`
	// The Id of the WebHook
	Id string `json:"id,omitempty"`
	// The type of the webhook JIT_POLICY WebHookJitPolicy
	Mode string `json:"mode,omitempty"`
	// The name of the WebHook
	Name string `json:"name"`
	// The Id of the org for which the WebHook is being added
	OrgId string `json:"orgId,omitempty"`
	// The Id of the service provider for which the WebHook is being added
	ServiceproviderId string `json:"serviceproviderId,omitempty"`
	// The status of the WebHook ACTIVE WebHookActive DELETED WebHookDeleted
	Status string `json:"status,omitempty"`
	// The last updated timestamp of the workloadcluster details
	Updated time.Time `json:"updated,omitempty"`
	// The Id of the user by whom the workloadcluster details were last updated
	WhoUpdated string `json:"whoUpdated,omitempty"`
}
