/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

// NetworkSummary represents the response format of network summary associated object count details
type NetworkSummary struct {
	// Number of App Connectors associated with the network
	AppConnectorCount int64 `json:"appConnectorCount,omitempty"`
	// Number of Apps associated with the network
	AppCount int64 `json:"appCount,omitempty"`
}
