/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

// AppSecretsStoreAttributes represents the format of attributes for App-SecretsStore association
type UserPswdAttributes struct {
	Pswd *Key `json:"pswd,omitempty"`
	User *Key `json:"user,omitempty"`
}
