/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

// BAUrlAliasSettings represents the settings required for configure URL alias
type BaUrlAliasSettings struct {
	// Id of the certificate which matches with the CNAME domain
	CertId string `json:"certId"`
	// CNAME associated with the domain
	Cname string `json:"cname"`
}
