/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

// AppEndpointIdpGroupAttributes represents the request format of Attributes of an AppEndpoint
type AppEndpointIdpGroupAttributes struct {
	GroupId   string `json:"groupId,omitempty"`
	GroupName string `json:"groupName,omitempty"`
}
