/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

import (
	"time"
)

// AppRoleDbUsers represents the response format of the details of the role with dbUsers
type AppRoleDbUsers struct {
	AppRoleAttributes *AppRoleAttributes `json:"appRoleAttributes,omitempty"`
	Attributes        IsRoleAttributes   `json:"attributes,omitempty"`
	// The creation timestamp of the role
	Created time.Time `json:"created,omitempty"`
	// The description of the role
	Description string `json:"description,omitempty"`
	// The Id of the role
	Id string `json:"id"`
	// The name of the role
	Name string `json:"name"`
	// The Id of the org for which the role is associated
	OrgId string `json:"orgId,omitempty"`
	// The ID of the app that created the role
	ResourceId string `json:"resourceId,omitempty"`
	// The resource type of resource associated NONE RoleAppResourceTypeNone IAMROLE RoleAppResourceTypeIamRole IDPGROUP RoleAppResourceTypeIdpGroup
	ResourceType string `json:"resourceType,omitempty"`
	// The scope of the role AUTHORIZATION RoleScopeAuthorization LOGIN RoleScopeLogin RESOURCE RoleScopeResource
	Scope string `json:"scope,omitempty"`
	// The status of the role (ACTIVE/DISABLED/DELETED) ACTIVE RoleActive
	Status string `json:"status,omitempty"`
	// The type of the role INTERNAL RoleTypeInternal EXTERNAL RoleTypeExternal
	Type_ string `json:"type,omitempty"`
	// The last updated timestamp of the role
	Updated time.Time `json:"updated,omitempty"`
	// The Id of the user by whom the role was last updated
	WhoUpdated string `json:"whoUpdated,omitempty"`
}
