/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

// Service Provider Approval config attributes
type ServiceProviderApprovalConfig struct {
	ClaimName  string   `json:"claimName,omitempty"`
	ClaimValue []string `json:"claimValue,omitempty"`
}
