/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

// ApiKeyAttributes represents the format of credential apikey attributes for App-SecretsStore association
type ApiKeyAttributes struct {
	Keys []Key `json:"keys,omitempty"`
}

func (a ApiKeyAttributes) IsSecretsStoreAttributes() {
}
