/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

// AppEndpointDefaultDbAttributes represents the request format of DB Attributes of an AppEndpoint
type AppEndpointDefaultDbAttributes struct {
	DbConfig *AppEndpointPostgresAttributesDbConfig `json:"dbConfig,omitempty"`
	DbProxy  string                                 `json:"dbProxy,omitempty"`
	Region   string                                 `json:"region,omitempty"`
	StartUri string                                 `json:"startUri,omitempty"`
	UbClient string                                 `json:"ubClient,omitempty"`
}
