/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

// AppEndpointRDPAttributes represents the request format of Attributes of an AppEndpoint
type AppEndpointRdpAttributes struct {
	UbClient string `json:"ubClient,omitempty"`
}
