/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

import (
	"time"
)

// Icon represents the response format about the details of the  icon
type Icon struct {
	// The attributes associated with the icon type
	Attributes interface{} `json:"attributes,omitempty"`
	// The creation timestamp of the  icon
	Created time.Time `json:"created,omitempty"`
	// The Id of the  icon
	Id string `json:"id"`
	// The name of the  icon
	Name string `json:"name"`
	// The Id of the org for which the  icon is associated with
	OrgId string `json:"orgId,omitempty"`
	// The status of the  icon object (ACTIVE/DELETED) ACTIVE IconStatusActive DISABLED IconStatusDisabled
	Status string `json:"status,omitempty"`
	// The type of the  icon EMOJI IconTypeEmoji FILE IconTypeFileBlob URL IconTypeUrl
	Type_ string `json:"type"`
	// The last updated timestamp of the  icon
	Updated time.Time `json:"updated,omitempty"`
	// The value associated with the icon type
	Value string `json:"value,omitempty"`
	// The Id of the user by whom the  icon was last updated
	WhoUpdated string `json:"whoUpdated,omitempty"`
}
