/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

// AppEndpointMySQLAttributesDbConfig represents the request format of database configuration for MySQL
type AppEndpointMySqlAttributesDbConfig struct {
	TlsCfgOptions *AppEndpointDbTlsConfigOptions `json:"tlsCfgOptions,omitempty"`
	TlsConfig     *AppEndpointMySqlTlsConfig     `json:"tlsConfig,omitempty"`
}
