/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

// AppAuthnOidcEndpoints represents the response format of OIDC endpoints for an app to communicate with IDP. For more info refer to OIDC specification
type AppAuthnOidcEndpoints struct {
	AuthzUrl        string `json:"authzUrl,omitempty"`
	IssuerUrl       string `json:"issuerUrl,omitempty"`
	JwksUrl         string `json:"jwksUrl,omitempty"`
	LogoutUrl       string `json:"logoutUrl,omitempty"`
	OpenIdConfigUrl string `json:"openIdConfigUrl,omitempty"`
	TokenUrl        string `json:"tokenUrl,omitempty"`
	UserInfoUrl     string `json:"userInfoUrl,omitempty"`
}
