/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

// UpdateAppTag represents the request format for updating an existing app tag
type UpdateAppTag struct {
	ApprovalConfig *ServiceProviderApprovalConfig `json:"approvalConfig,omitempty"`
	// Apptag is used for compliance purpose or not
	ComplianceUse bool `json:"complianceUse,omitempty"`
	// The description for the network
	Description string `json:"description,omitempty"`
	// The name of an app tag
	Name string `json:"name,omitempty"`
	// The scope of the app tag (ACCESSPOLICY) ACCESSPOLICY AppTagScopeAccessPolicy RESOURCE AppTagScopeResource
	Scope string `json:"scope,omitempty"`
}
