/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

import (
	"time"
)

// Network represents the response format of network details
type Network struct {
	// The creation timestamp of the network
	Created time.Time `json:"created,omitempty"`
	// The description for the network
	Description       string `json:"description,omitempty"`
	DomainHostingType string `json:"domainHostingType,omitempty"`
	// The GeoDnsCname associated with the network
	GeoDnsCname string `json:"geoDnsCname,omitempty"`
	// The Id of the network
	Id string `json:"id"`
	// A flag to determine whether the network is of type default
	IsDefault bool `json:"isDefault,omitempty"`
	// WAF status of the network object
	IsWAF bool `json:"isWAF,omitempty"`
	// The name of the network
	Name string `json:"name"`
	// The Id of the org associated with the network
	OrgId   string          `json:"orgId,omitempty"`
	Summary *NetworkSummary `json:"summary,omitempty"`
	// The type of the network LOCAL NetworkLocal SAAS_CLIENT NetworkSaasClient SAAS_SERVER NetworkSaasServer INTERCONNECT NetworkInterconnect
	Type_ string `json:"type,omitempty"`
	// The last updated timestamp of the network
	Updated time.Time `json:"updated,omitempty"`
	// The Id of the user by whom the org was last updated
	WhoUpdated string `json:"whoUpdated,omitempty"`
}
