/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

import (
	"time"
)

// AuthProvider represents the response format of auth provider details
type AuthProvider struct {
	// The hosted resources the AuthProvider manages (UNKNOWN/BASIC/ADVANCED) BASIC AuthProviderHostingTypeBasic ADVANCED AuthProviderHostingTypeAdvanced UNKNOWN AuthProviderHostingTypeUnknown
	ApHostingType string `json:"apHostingType,omitempty"`
	// The app type associated with Auth Provider (WEB/NATIVE) WEB AuthProviderAppTypeWeb NATIVE AuthProviderAppTypeNative
	AppType    string                    `json:"appType,omitempty"`
	Attributes *IsAuthProviderAttributes `json:"attributes,omitempty"`
	// Cname of the org app Launchpad domain(for hosting type UBYON/ENTERPRISE)
	Cname string `json:"cname,omitempty"`
	// The creation timestamp of the auth provider
	Created time.Time `json:"created,omitempty"`
	// The description for an auth provider
	Description string `json:"description,omitempty"`
	// The display name of an auth provider which will be used to display in login page
	DisplayName string `json:"displayName"`
	EntityId    string `json:"entityId,omitempty"`
	// The Id of the auth provider
	Id string `json:"id"`
	// Use Ubyon Identity as a service (ENABLED/DISABLED) default ENABLED ENABLED AuthProviderIdaasEnabled DISABLED AuthProviderIdaasDisabled
	Idaas string `json:"idaas,omitempty"`
	// Boolean to set the auth provider as default
	IsDefault bool             `json:"isDefault,omitempty"`
	Mfa       *AuthProviderMfa `json:"mfa,omitempty"`
	// The name of the auth provider
	Name string `json:"name"`
	// The Id of the org associated with the auth provider
	OrgId string `json:"orgId,omitempty"`
	// The protocol associated with the auth provider OIDC AuthProviderProtocolOidc SAML2 AuthProviderProtocolSaml2 NONE AuthProviderProtocolNone
	Protocol string `json:"protocol,omitempty"`
	// The type of auth provider OTHER AuthServiceProviderTypeOther GOOGLE AuthServiceProviderTypeGoogle AZURE AuthServiceProviderTypeAzure OKTA AuthServiceProviderTypeOkta PING AuthServiceProviderTypePing AUTH0 AuthServiceProviderTypeStringAuth0
	ProviderType string `json:"providerType,omitempty"`
	// The URL for redirecting after the auth provider authentication process
	RedirectUrl string `json:"redirectUrl"`
	// The URL to redirect the user after signout
	SignoutRedirectUrl string `json:"signoutRedirectUrl,omitempty"`
	// The status of the auth provider STAGED AuthProviderStatusStaged ACTIVE AuthProviderStatusActive DISABLED AuthProviderStatusDisable
	Status string `json:"status,omitempty"`
	// The type of an auth provider INTERNAL AuthProviderTypeInternal EXTERNAL AuthProviderTypeExternal
	Type_ string `json:"type"`
	// The last updated timestamp of the auth provider
	Updated time.Time `json:"updated,omitempty"`
	// The Id of the user by whom the org was last updated
	WhoUpdated string `json:"whoUpdated,omitempty"`
}
