/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

// UpdateAppSecretsStore represents the request format for updating a AppSecretsStore  secrets store association
type UpdateAppSecretsStore struct {
	Attributes *AppSecretsStoreAttributes `json:"attributes"`
}
