/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

// The structure of ResourceOwnerChannel
type ResourceOwnerChannel struct {
	Type_ string `json:"type,omitempty"`
	Value string `json:"value,omitempty"`
}
