/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

// JwtAttributes represents the format of credential jwtkey attributes for App-SecretsStore association
type JwtAttributes struct {
	Keys []Key `json:"keys,omitempty"`
}
