/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

// NewAppSecretsStore represents the request format for creating a appp secretsstore association
type NewAppSecretsStore struct {
	// The Id of the org to which app to secretsstore is associated
	OrgId string `json:"OrgId,omitempty"`
	// The Id of the app to which the secretsstore is associated
	AppId      string                     `json:"appId"`
	Attributes *AppSecretsStoreAttributes `json:"attributes"`
	// The Id of the secretsstore to which app is associated
	SecretsStoreId string `json:"secretsStoreId"`
}
