/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

// CompositeAppResourceRaw represents the request format for composte app for http methods POST and PATCH
type CompositeAppResourceRaw struct {
	// The attributes of the resource associated with the app oneOf: \\- $ref: '#/components/schemas/NewApp' \\- $ref: '#/components/schemas/UpdateApp' \\- type: array items:  $ref: '#/components/schemas/NewAppEndpointRaw' \\- type: array items:  $ref: '#/components/schemas/UpdateAppEndpointRaw' \\- type: array items:  $ref: '#/components/schemas/NewAppTag' \\- type: array items:  $ref: '#/components/schemas/NewNetwork' \\- type: array items:  $ref: '#/components/schemas/NewAuthProvider' \\- type: array items:  $ref: '#/components/schemas/NewIcon' \\- type: array items: $ref: '#/components/schemas/UpdateIconRaw' \\- type: array items:  type: string
	Body interface{} `json:"body"`
	//Body interface{} `json:"body"`
	// The http method that needs to be applied on the composite app POST HttpMethodPost PATCH HttpMethodPatch DELETE HttpMethodDelete
	Method      string `json:"method"`
	ReferenceId string `json:"referenceId"`
	// The type of the resource associated with the app APPTAG AppResourceTag NETWORK AppResourceNetwork APPENDPOINT AppResourceEndpoint APP AppResourceApp APPCONNECTOR AppResourceAppConnector APPLAUNCHPAD AppResourceAppLaunchpad AUTHPROVIDER AppResourceAuthProvider ICON AppResourceIcon RESOURCEOWNER AppResourceResourceOwner APPROLE AppResourceAppRole APPWEBHOOK AppResourceAppWebHook APPSECRETSSTORE AppResourceAppSecretsStore
	Type_ string `json:"type"`
}
