/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

// SecretsStoreCredX509Pair represents the Secrets Store Credentials of type Certificate including the private key
type SecretsStoreCredX509Pair struct {
	CaCertPath     string `json:"caCertPath,omitempty"`
	PrivateKeyPath string `json:"privateKeyPath"`
	PublicKeyPath  string `json:"publicKeyPath"`
	SecretsStoreId string `json:"secretsStoreId"`
}
