/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

// NewBrowserAccessSettings represent the request format for enabling browser access for an appendpoint
type NewBrowserAccessSettings struct {
	// The attributes to enable browser access for the application oneOf: \\- $ref: '#/components/schemas/BAHttpAttributes' \\- $ref: '#/components/schemas/BAHttpsAttributes' \\- $ref: '#/components/schemas/BASshAttributes'
	Attributes interface{} `json:"attributes,omitempty"`
	// Hosting type for the application settings (UBYON|ENTERPRISE) UBYON ResourceHostingTypeUbyon ENTERPRISE ResourceHostingTypeEnterprise
	HostingType string `json:"hostingType,omitempty"`
	// The resource type of the app (UBYON/ENTERPRISE) UBYON ResourceTypeUbyon ENTERPRISE ResourceTypeEnterprise CLOUD ResourceTypeCloud
	ResourceType string `json:"resourceType,omitempty"`
	// Enable/disable URL alias for the application
	UrlAlias         bool                `json:"urlAlias,omitempty"`
	UrlAliasSettings *BaUrlAliasSettings `json:"urlAliasSettings,omitempty"`
}
