/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

// AppEndpointK8SAttributes represents the request format of Attributes of an AppEndpoint
type AppEndpointK8SAttributes struct {
	// K8S access token to access the cluster
	K8sAccessToken string `json:"k8sAccessToken,omitempty"`
	// Whether the endpoint is accessible via the native ubyon client SSO AppEndpointK8SAttributesAuthenticationTypeSSO SERVICEACCOUNT AppEndpointK8SAttributesAuthenticationTypeServiceAccount
	K8sAuthenticationType string `json:"k8sAuthenticationType,omitempty"`
	// Whether the endpoint is accessible via the native ubyon client ENABLED AppEndpointK8SAttributesUbClientEnabled DISABLED AppEndpointK8SAttributesUbClientDisabled
	K8sUbClient string `json:"k8sUbClient,omitempty"`
	// User identity to authorise access the cluster ENABLED AppEndpointK8SAttributesUserIdentityEnabled DISABLED AppEndpointK8SAttributesUserIdentityDisabled
	K8sUserIdentity string `json:"k8sUserIdentity,omitempty"`
}
