/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

// AppEndpointSSHAttributes represents the request format of Attributes of an AppEndpoint
type AppEndpointSshAttributes struct {
	BypassList []string `json:"bypassList,omitempty"`
	SshProxy   string   `json:"sshProxy,omitempty"`
	UbClient   string   `json:"ubClient,omitempty"`
}
