/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

// UpdateApp represents the request format for updating an existing app
type UpdateApp struct {
	ApprovalConfig *ServiceProviderApprovalConfig `json:"approvalConfig,omitempty"`
	// The ID of the asset the app was created from
	AssetId        string             `json:"assetId,omitempty"`
	Attributes     *IsAppAttributes   `json:"attributes,omitempty"`
	Authentication *AppAuthentication `json:"authentication,omitempty"`
	// The description for the app
	Description string `json:"description,omitempty"`
	// The app authentication is enabled or not (True/False)
	IsAuthnEnabled bool `json:"isAuthnEnabled,omitempty"`
	// The manager of the cloud resource NONE ManagedByNone AWS ManagedByAws AZURE ManagedByAzure GCP ManagedByGcp SNOWFLAKE ManagedBySnowflake DATABRICKS ManagedByDatabricks
	ManagedBy string `json:"managedBy,omitempty"`
	// The name of an app
	Name string `json:"name,omitempty"`
	// The service provider ID that the app is associated to
	ServiceProviderId string `json:"serviceProviderId,omitempty"`
	// The service type of the app NONE ServiceTypeNone IAMROLE ServiceTypeIamRole IDPGROUP ServiceTypeIdpGroup RESOURCEOWNER ServiceTypeResourceOwner MESHAPP ServiceTypeMeshApp ONCALL ServiceTypeOnCall RDS ServiceTypeRDS EKS ServiceTypeEKS SSM ServiceTypeSSM S3 ServiceTypeS3 SAAS ServiceTypeSaas BLOB ServiceTypeBlob
	ServiceType string `json:"serviceType,omitempty"`
	// The subcategory of the app NONE AppSubCategoryNone MACHINE AppSubCategoryMachine DESKTOP AppSubCategoryDesktop CLUSTER AppSubCategoryCluster DATASOURCE AppSubCategoryDataSource WEB AppSubCategoryWeb AWS AppSubCategoryAws GCP AppSubCategoryGcp AZURE AppSubCategoryAzure OCI AppSubCategoryOci OKTA AppSubCategoryOkta GOOGLE AppSubCategoryGoogle PING AppSubCategoryPing UBYON AppSubCategoryUbyon IBM AppSubCategoryIbm PAGERDUTY AppSubCategoryPagerDuty OPSGENIE AppSubCategoryOpsGenie
	SubCategory string `json:"subCategory,omitempty"`
	// The Type of the app (PUBLIC|PRIVATE|SHORTCUT) PUBLIC AppPublic PRIVATE AppPrivate SHORTCUT AppShortcut
	Type_ string `json:"type,omitempty"`
}
