/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

// AppAuthentication represents the configuration required to integrate with ubyon idaas
type AppAuthentication struct {
	Attributes *IsAppAuthnAttributes `json:"attributes,omitempty"`
	Protocol   string                `json:"protocol,omitempty"`
}
