/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

// CompositeAppResource represents the response format for a composite app create or update
type CompositeAppResource struct {
	App *App `json:"app,omitempty"`
	// The attributes associated of the network
	AppConnectors []AppConnector `json:"appConnectors,omitempty"`
	// The attributes associated of the app endpoint
	AppEndpoints []AppEndpointRaw `json:"appEndpoints,omitempty"`
	// The attributes of the associated app Launchpad
	AppLaunchpads []AppLaunchpad `json:"appLaunchpads,omitempty"`
	// The App Secrets store association
	AppSecretsStores []AppSecretsStore `json:"appSecretsStores,omitempty"`
	// The attributes associated of the app tag
	AppTags []AppTag `json:"appTags,omitempty"`
	// The attributes of the associated auth provider
	AuthProviders []AuthProvider `json:"authProviders,omitempty"`
	CloudAccount  *CloudAccount  `json:"cloudAccount,omitempty"`
	// The attributes of the associated icon
	Icons []Icon `json:"icons,omitempty"`
	// The attributes associated of the network
	Networks []Network `json:"networks,omitempty"`
	// The attributes associated of the network
	ResourceOwners []ResourceOwner `json:"resourceOwners,omitempty"`
	// The App role with dbUsers
	Roles []AppRoleDbUsers `json:"roles,omitempty"`
	// The App Webhook association
	Webhooks []WebHook `json:"webhooks,omitempty"`
}
