/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

// BASshAttributes represents the ssh attributes required for browser access
type BaSshAttributes struct {
	// Maximum number of concurrent SSH connections
	MaxConnections int64 `json:"maxConnections,omitempty"`
	// The Uri to redirect the users after entering the application. Defaults to \"/ssh\"
	StartUri string `json:"startUri,omitempty"`
}
