/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

import (
	"time"
)

// AppTag represents the response format of app tag details
type AppTag struct {
	ApprovalConfig *ServiceProviderApprovalConfig `json:"approvalConfig,omitempty"`
	// Apptag is used for compliance purpose or not
	ComplianceUse bool `json:"complianceUse,omitempty"`
	// The creation timestamp of the app tag
	Created time.Time `json:"created,omitempty"`
	// The description for the network
	Description string `json:"description,omitempty"`
	// The Id of the app tag
	Id string `json:"id"`
	// A flag to determine whthether the apptag is default or not
	IsDefault bool `json:"isDefault,omitempty"`
	// The name of the app tag
	Name string `json:"name"`
	// The Id of the org associated with the app tag
	OrgId string `json:"orgId,omitempty"`
	// The scope of the app tag ACCESSPOLICY AppTagScopeAccessPolicy RESOURCE AppTagScopeResource
	Scope string `json:"scope,omitempty"`
	// The last updated timestamp of the app tag
	Updated time.Time `json:"updated,omitempty"`
	// The Id of the user by whom the org was last updated
	WhoUpdated string `json:"whoUpdated,omitempty"`
}
