/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

import (
	"time"
)

// AppSecretsStore represents the response format of a AppSecretsStore secretsstore association
type AppSecretsStore struct {
	// The Id of the app to which the secretsstore is associated
	AppId      string                     `json:"appId"`
	Attributes *AppSecretsStoreAttributes `json:"attributes"`
	// The creation timestamp of the AppSecretsStore secretsstore
	Created time.Time `json:"created,omitempty"`
	// The Id of the org to which app to secretsstore is associated
	OrgId string `json:"orgId,omitempty"`
	// The Id of the app to which the secretsstore is associated
	SecretsStoreId string `json:"secretsStoreId"`
	// The last updated timestamp of the AppSecretsStore secretsstore
	Updated time.Time `json:"updated,omitempty"`
}
