/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

// NewAppRole represents the request format for creating an app role association
type NewAppRole struct {
	// The Id of the org to which app to role is associated
	OrgId string `json:"OrgId,omitempty"`
	// The Id of the app to which the role is associated
	AppId      string             `json:"appId"`
	Attributes *AppRoleAttributes `json:"attributes,omitempty"`
	// The Id of the role to which app is associated
	RoleId string `json:"roleId"`
}
