/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

// AppEndpointDbTlsCfgLocSecretsStore represents the tls config for database proxy
type AppEndpointDbTlsCfgLocSecretsStore struct {
	DbServerCaPath      *SecretsStoreCredX509Cert `json:"dbServerCaPath,omitempty"`
	ProxyServerCertPath *SecretsStoreCredX509Pair `json:"proxyServerCertPath,omitempty"`
}
