/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

// AppEndpointPostgresTlsConfig represents the request format of tls configuration of an endpoint
type AppEndpointPostgresTlsConfig struct {
	CertId string `json:"certId,omitempty"`
	DbCA   string `json:"dbCA,omitempty"`
}
