/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

import "encoding/json"

// AppEndpointDbTlsConfigOptions represents the tls config for database proxy
type AppEndpointDbTlsConfigOptions struct {
	// NONE AppEndpointDbTlsCfgLocTypeNone DIRECT AppEndpointDbTlsCfgLocTypeDirect SECRETS_STORE AppEndpointDbTlsCfgLocTypeSecretsStore
	CfgLocType  string                   `json:"cfgLocType,omitempty"`
	CfgLocation IsAppEndpointDbTlsCfgLoc `json:"cfgLocation,omitempty"`
}

func (dtcc *AppEndpointDbTlsConfigOptions) UnmarshalJSON(bs []byte) error {
	var taae map[string]interface{}
	err := json.Unmarshal(bs, &taae)
	if err != nil {
		return err
	}
	type appEndpointDbTlsConfigCmn AppEndpointDbTlsConfigOptions
	fdtcc := (*appEndpointDbTlsConfigCmn)(dtcc)
	switch taae["cfgLocType"] {
	case "SECRETS_STORE":
		fdtcc.CfgLocation = &AppEndpointDbTlsCfgLocSecretsStore{}
	case "NONE":
		fdtcc.CfgLocation = &AppEndpointDbTlsCfgLocNone{}
	default:
		fdtcc.CfgLocation = &AppEndpointDbTlsCfgLocDirect{}
	}

	err = json.Unmarshal(bs, &fdtcc)
	if err != nil {
		return err
	}

	return nil
}
