/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

import (
	"time"
)

// BrowserAccessSettings represent the response format of browser access settings for an appendpoint
type BrowserAccessSettings struct {
	// The Id of the appendpoint
	AppEndpointId string `json:"appEndpointId,omitempty"`
	// The attributes to enable browser access for the application oneOf: \\- $ref: '#/components/schemas/BAHttpAttributes' \\- $ref: '#/components/schemas/BAHttpsAttributes' \\- $ref: '#/components/schemas/BASshAttributes'
	Attributes interface{} `json:"attributes,omitempty"`
	// The creation timestamp of the broswer settings
	Created time.Time `json:"created,omitempty"`
	// Hosting type for the application settings (UBYON|ENTERPRISE) UBYON ResourceHostingTypeUbyon ENTERPRISE ResourceHostingTypeEnterprise
	HostingType string `json:"hostingType,omitempty"`
	// The Id of the org associated with the browser settings
	OrgId string `json:"orgId,omitempty"`
	// The resource type of the app (UBYON/ENTERPRISE) UBYON ResourceTypeUbyon ENTERPRISE ResourceTypeEnterprise CLOUD ResourceTypeCloud
	ResourceType string `json:"resourceType,omitempty"`
	// The last updated timestamp of the browser settings
	Updated time.Time `json:"updated,omitempty"`
	// Enable/Disable URL alias for the application
	UrlAlias         bool                `json:"urlAlias,omitempty"`
	UrlAliasSettings *BaUrlAliasSettings `json:"urlAliasSettings,omitempty"`
	// The Id of the user by whom the settings was last updated
	WhoUpdated string `json:"whoUpdated,omitempty"`
}
