/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

// WebHookAttributes specify the attributes struct of a webhook
type WebHookAttributes struct {
	AuthScheme *WebHookAuthScheme `json:"authScheme,omitempty"`
	Headers    []WebHookHeaders   `json:"headers,omitempty"`
	Uri        string             `json:"uri,omitempty"`
}
