/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

// DefaultCredentialsAttributes represents the format of credential default attributes for App-SecretsStore association
type DefaultCredentialsAttributes struct {
}
