/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

import (
	"time"
)

// AppLaunchpad represents the request format for a app Launchpad to be created
type AppLaunchpad struct {
	// Id of the certificate which matches with the CNAME app Launchpad domain
	CertId string `json:"certId,omitempty"`
	// The creation timestamp of the app
	Created time.Time `json:"created,omitempty"`
	// The description for app Launchpad
	Description string `json:"description,omitempty"`
	// Fqdn associated with the app Launchpad
	Fqdn string `json:"fqdn,omitempty"`
	// The hosting option of the app Launchpad (UBYON/ENTERPRISE) UBYON ResourceHostingTypeUbyon ENTERPRISE ResourceHostingTypeEnterprise
	HostingType string `json:"hostingType,omitempty"`
	// The Id of the icon used by the app Launchpad
	IconId string `json:"iconId,omitempty"`
	// The Id of the app
	Id string `json:"id"`
	// The name of an app Launchpad
	Name string `json:"name,omitempty"`
	// The Id of the org associated with the app
	OrgId string `json:"orgId,omitempty"`
	// The resource the AuthProvider manages (UBYON/ENTERPRISE) UBYON ResourceTypeUbyon ENTERPRISE ResourceTypeEnterprise CLOUD ResourceTypeCloud
	ResourceType string `json:"resourceType,omitempty"`
	// The status of the app Launchpad (ACTIVE/DISABLED) ACTIVE AppLaunchpadActive DISABLED AppLaunchpadDisabled
	Status string `json:"status,omitempty"`
	// The last updated timestamp of the app
	Updated time.Time `json:"updated,omitempty"`
}
