/*
 * Configuration API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package corecfgclient

// AuthProviderMfa represents the request format of MFA attributes of an AuthProvider
type AuthProviderMfa struct {
	Launchpad  string `json:"launchpad,omitempty"`
	Management string `json:"management,omitempty"`
}
